// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore mobx-form-schema.d.ts will be generated by Rollup
declare module './mobx-form-schema' {
  interface TypesConfiguration {
    experimentalDecorators: true;
  }
}

export {};
