name: Cron

on:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Remove main package.json
        run: |
          rm package.json
          rm yarn.lock

      - name: Build Docs
        run: |
          cd packages/docs
          yarn install
          yarn build
          cd ../..

      - name: Run tests
        run: |
          cd packages/tests
          yarn install
          yarn test:modern
          yarn test:legacy
          cd ../..
